server:
  port: 9192

spring:
  datasource:
    username: root
    password: toor
    url: jdbc:mysql://localhost:3306/Student_DB?createDatabaseIfNotExist=true
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      format_sql: true
